version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trello-vertical-timeline"
s3_bucket = "iglu-deployments-london"
s3_prefix = "trello-vertical-timeline"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PoolDomainName=\"vertical-timeline\""
