AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-sam-flask

  Sample SAM Template for hello-sam-flask

Globals:
  Function:
    Timeout: 10

Parameters:
  PoolDomainName:
    Type: String
    Description: Domain name for Cognito Hosted UI
    Default: auth-flask-test

Resources:
  WebAppFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: webapp/
      Handler: app.app
      Runtime: python3.8
      Events:
        AllRequests:
          Type: HttpApi
          Properties:
            ApiId: !Ref PublicApi
            PayloadFormatVersion: "1.0"

  PublicApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration: True
      # StageName: !Ref StageName
      # Tags:
      #   Tag: Value
      # AccessLogSettings:
      #   DestinationArn: !GetAtt AccessLogs.Arn
      #   Format: $context.requestId






# User pool - simple configuration 
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      AdminCreateUserConfig: 
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes: 
        - email
      MfaConfiguration: "OFF"
      Policies: 
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      Schema: 
        - AttributeDataType: String
          Mutable: true
          Name: name
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: email
          Required: true
      UsernameAttributes: 
        - email

  # User Pool client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      AllowedOAuthFlows: 
        - code
        # - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes: 
        - phone
        - email
        - openid
        - aws.cognito.signin.user.admin
        - profile
      ClientName: FlaskAppClient
      CallbackURLs:
        - http://localhost:5000/aws_cognito_redirect
        - https://w467k2ss1h.execute-api.eu-west-1.amazonaws.com/aws_cognito_redirect
      # LogoutURLs: 
      #   - !Sub "https://${WebSubdomainName}.${DomainName}"
      # ExplicitAuthFlows: 
      #   - ALLOW_USER_PASSWORD_AUTH
      #   - ALLOW_USER_SRP_AUTH
      #   - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders: 
        - COGNITO
      UserPoolId: !Ref UserPool

  # User pool domain name - set to 
  PoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: !Ref PoolDomainName
      UserPoolId: !Ref UserPool



Outputs:
  HelloWorldApi:
    Description: "API Gateway v2 endpoint URL for default stage for Hello World function"
    Value: !Sub "https://${PublicApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  UserPoolClientId:
      Description: UserPoolClient ID
      Value: !Ref UserPoolClient
  UserPoolId:
      Description: UserPool ID
      Value: !Ref UserPool
  UserPoolDomain:
      Description: UserPool Domain
      Value: !Ref PoolDomain