# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r vertical-timeline/requirements.txt
        python -m pip install lib/dynamodb-repository/
        python -m pip install lib/verticaltimeline-common/
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: >
        AWS_DEFAULT_REGION=us-east-1
        AWS_ACCESS_KEY_ID=abc 
        AWS_SECRET_ACCESS_KEY=xyz 
        pytest tests
    - name: Prepare configuration file
      run: |
        echo test > vertical-timeline/webapp/application.cfg
        echo test2 >> vertical-timeline/webapp/application.cfg
        cat vertical-timeline/webapp/application.cfg
    - name: Build
      run: sam build
